spring.application.name=API-GATEWAY

server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Enable service discovery
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true


# JWT
jwt.secret=MySuperSecretKeyForEmployeeManagementPlatform2026MySuperSecretKey

# Actuator
management.endpoints.web.exposure.include=*

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=Employee Service
springdoc.swagger-ui.urls[0].url=/employee-service/v3/api-docs

springdoc.swagger-ui.urls[1].name=User Service
springdoc.swagger-ui.urls[1].url=/user-service/v3/api-docs

springdoc.swagger-ui.urlsPrimaryName=Employee Service

springdoc.swagger-ui.urls[2].name=Auth Service
springdoc.swagger-ui.urls[2].url=/auth-service/v3/api-docs

server.forward-headers-strategy=none
springdoc.swagger-ui.disable-swagger-default-url=true


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.use-root-path=true